#!/bin/bash

echo "       __________"
echo "       |         |"
echo "       |         |"
echo "       |         |"
echo "                 |"
echo "                 |"
echo "                 |"
echo "                 |"
echo "                 |"
echo "                 |"
echo "                 |"
echo "                 |"
echo "_________________|"