#!/bin/bash
#Funciones con los dibujos del ahorcado
function cuerpo_0 () {
echo "          ___________"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "_____________________|"
}
function cuerpo_1 () {
echo "          ___________"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "       __/_\__       |"
echo "        |*_*|        |"
echo "         \ /         |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "_____________________|"
}

function cuerpo_2 () {
echo "          ___________"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "       __/_\__       |"
echo "        |*_*|        |"
echo "         \ /         |"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "_____________________|"
}

function cuerpo_3 () {
echo "          ___________"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "       __/_\__       |"
echo "        |*_*|        |"
echo "         \ /         |"
echo "          |______    |"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "_____________________|"
}

function cuerpo_4 () {
echo "          ___________"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "       __/_\__       |"
echo "        |*_*|        |"
echo "         \ /         |"
echo "    ______|______    |"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "_____________________|"
}

function cuerpo_5 () {
echo "          ___________"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "       __/_\__       |"
echo "        |*_*|        |"
echo "         \ /         |"
echo "    ______|______    |"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "           \         |"
echo "            \        |"
echo "             \       |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "_____________________|"
}

function cuerpo_6 () {
echo "          ___________"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "       __/_\__       |"
echo "        |x_x|        |"
echo "         \ /         |"
echo "    ______|______    |"
echo "          |          |"
echo "          |          |"
echo "          |          |"
echo "         / \         |"
echo "        /   \        |"
echo "       /     \       |"
echo "                     |"
echo "                     |"
echo "                     |"
echo "_____________________|"
}